### ISSUE TITLE
Unable to Verify

### ISSUE THREAD

**Issue by eljobe** [obiba/amber-studio#2]
I was able to get the smtp configuration set up correctly, and I seeded the database with the `ADMINISTRATOR_EMAIL` and `ADMINISTRATOR_PWD` values in my local `.env` file.

The email was sent to my email address and I clicked the verification link, but then I saw this:

![image](https://user-images.githubusercontent.com/679924/212487328-3602b385-9613-4663-aa19-62173f5193b6.png)

I'm not sure how to debug this further. But, I will, of course head to the source code and see if anything pops up.

If you can give me any advice, I'd appreciate it. I'm trying to help my wife evaluate the OBiBA offerings for a research project she is doing in music therapy, and between not being able to get the obiba/onyx-demo to build and not being able to get a proper installation configured for the amber suite, I'm not sure I can really recommend it.

**Comment by ymarcon** [comment]
See documentation (writing is in progress): https://amberdoc.obiba.org/
It is recommended to use docker: https://github.com/obiba/docker-amber
